### PR TITLE
my website

### PR DESCRIPTION
**Pull request by Madhavman**
this is my website you can change according to you please don't mark spam i am a student of class 6 if any problem plesae tell me

### CODE REVIEW

**Comment by Preyash-tryin-to-code** [comment]
Hiiiii @Madhavman !!, We are very glad🤩 to see a kid in 6th standard making such a beautiful website, keep up the good work boiii🤗.

**Review by Preyash-tryin-to-code — APPROVED** [review]

**Comment by Madhavman** [comment]
thanks bro for merging can you give me your more reposiotory

**Comment by Madhavman** [comment]
Can you gave me more resposrtory like design about page i willl do

**Comment by Preyash-tryin-to-code** [comment]
Heyyy! you can actually make a folder called "templates" and you can make generic templates and add them there.

**Comment by Madhavman** [comment]
Awesome, thanks! But i Don't know how to do ,if you tell and I gave you can
merge

**Comment by PranavViswanathan** [comment]
image
@Madhavman there is a folder called html-css templates, you can add them there.

**Comment by Madhavman** [comment]
Awesome, thanks! This website which I have gave

**Pull request merged**
